---
- name: Install some common editors
  become: true
  become_user: "{{ root_user }}"
  apt:
      name:
      - emacs
      - vim
      - nano
      - evince
      state: present

- name: install basic .vimrc
  copy:
    src: .vimrc
    dest: "${HOME}"
